Branch protection
AthosCommerce/snapfu pull request #19
Opened 2022-01-06 20:32 UTC by dkonieczek

## Changes
- add branch protection for production branch upon creating new site via init
- Requires 'Snap Action' status check to succeed
- disables required reviewers

2022-01-06 23:10 UTC, korgon requested changes
Apparently I forgot this option - could you please add this into the PR? Thanks!
![image](https://user-images.githubusercontent.com/5060400/148465241-8b0f19e9-b4ce-48f4-aa15-e801bec0e353.png)

2022-01-06 23:16 UTC, korgon requested changes

2022-01-06 23:16 UTC, korgon commented on src/init.js
> -		console.log();
This was here for spacing - maybe return it or add some spacing another way?

See spacing missing now before "The testing-branch-protection directory...":
![image](https://user-images.githubusercontent.com/5060400/148465759-30764aeb-2dfb-432e-a91d-13d9734fc880.png)

2022-01-06 23:18 UTC, korgon commented
Should we mention anything about checking out a new branch immediately since direct pushing to `production` is no longer accepted?

2022-01-07 15:34 UTC, dkonieczek commented
- Added admins to be enforced by branch protection rule. 
- Improved the logging and it's spacing. Also mentioned to create a new branch.

2022-01-07 15:38 UTC, korgon requested changes
Looks good! One last thing...

```
&& git checkout -b branch
```

Since people 'may' copy and paste this - I think we should use something like `mockup` or `development` or something similar instead of `branch`.

2022-01-07 15:54 UTC, korgon approved these changes

2022-01-07 16:49 UTC, merged